### ISSUE TITLE
how to make it console in the next line

### ISSUE THREAD

**Issue by weihomechen** [Chakroun-Anas/turbo-console-log#110]
![image](https://ifun.oss-cn-hangzhou.aliyuncs.com/tmp/WX20201126-143746.png)
my configuration  ：
![image](https://user-images.githubusercontent.com/16172317/100316420-70bf2480-2ff5-11eb-89de-d9787046a0bb.png)

**Comment by MariuzM** [comment]
yep started having same issue with this new update....

**Comment by Chakroun-Anas** [comment]
Hello @weihomechen , i just pushed a version that deal with the scenario that you shared, thank you so much for sharing and don't hesitate to share more problems in the futur so that we fix them and make the extension more robust 😉

**Comment by WaqqarSuleman** [comment]
Hi @Chakroun-Anas , I updated to the latest version but the issue persists. Please look into it.

**Comment by Chakroun-Anas** [comment]
Hello @WaqqarSuleman, the extension is now handling the shared scenario above: 

<img width="570" alt="Screenshot 2020-11-26 at 16 02 56" src="https://user-images.githubusercontent.com/35881867/100366286-f4324300-3000-11eb-913c-3332af63d1e1.png">

Please share the exacte code snippet where it's not working properly for you, thanks.

**Comment by WaqqarSuleman** [comment]
Please refer to the screenshot below:

![Screenshot from 2020-11-26 20-40-22](https://user-images.githubusercontent.com/74898820/100367144-c9a7b080-3027-11eb-9932-7aebae43d5fc.png)

**Comment by chakroun-anas-contentsquare** [comment]
Hello @WaqqarSuleman, this is a different use case than the first one, here you are trying to insert a log message related to deconstructed property, i will come with a fix for this also and let know when it's published, thank you for you feedback.

**Comment by Chakroun-Anas** [comment]
Hello @WaqqarSuleman, this is a different use case than the first one, here you are trying to insert a log message related to deconstructed property, i will come with a fix for this also and let know when it's published, thank you for you feedback.

**Comment by aguscha333** [comment]
Hi, I am on v2.1.5 and I am getting the following issue when commenting react native code:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/9297073/100908813-b32baa00-34aa-11eb-8f7c-fbd1534eb235.png">
I am trying to log the params constant and when I hit ctrl+alt+l then it adds the log but after the next line of actual code

**Comment by borishere** [comment]
Too many use cases are broken since last updates!

**Comment by MariuzM** [comment]
Yep agree with @borishere issues for me also

**Comment by chakroun-anas-contentsquare** [comment]
@aguscha333 Thank you for sharing,  at this stage a log message related to a deconstructed property is a known issue, see the two posts juste above your post. 

@borishere @MariuzM Can you please share with me code snippets for each use case where the extension fails to deduce the right line code where the log message should be inserted ? without this i'm afraid that i couldn't do much for you :/

**Comment by Chakroun-Anas** [comment]
@aguscha333 Thank you for sharing, at this stage a log message related to a deconstructed property is a known issue, see the two posts juste above your post.

@borishere @MariuzM Can you please share with me the code snippet for each use case where the extension fails to deduce the right line code for the log message to be inserted ? without this i'm afraid that i couldn't do much for you :/

**Comment by Chakroun-Anas** [comment]
@aguscha333 @WaqqarSuleman  I just pushed a version ((v2.1.6) ) that deals with what you shared, please test again and give me your feedback 😉

**Comment by WaqqarSuleman** [comment]
@Chakroun-Anas it seems to be working fine atm. Thanks!

**Comment by aaronkychan** [comment]
v2.1.6, still broken for me
![consolelogmisbehave](https://user-images.githubusercontent.com/7438968/105949151-975e1200-60af-11eb-8f09-6f71c91716bd.png)

**Comment by sebj54** [comment]
Hi @Chakroun-Anas, like the other users here, many use cases are broken since a previous update, especially for those like me who codes without semicolons

Since my codestyle breaks the "autodetect line to insert TCL" feature, I think a "force insert on next line" setting would be great.

Actually, TCL lines are more often on a wrong line than in the correct line. I often have to use Ctrl+F to find where my log has been inserted (it is a nightmare when you start to fold blocks) and then I have to move it manually. It also breaks the "comment all" and "remove all" features because the TCL line has been edited manually.

Thanks for your amazing extension anyway, it is still time-savy!

You can try this snippet if you'd like (select `this.foo`):
```js
export default {
    created() {
        this.foo()
        this.bar()
    },
    methods: {
        foo() {
            return 1 + 1
        },
        bar() {
            return 2 + 2
        },
    },
}
```

Hi @Chakroun-Anas, like the other users here, many use cases are broken since a previous update, especially for those like me who codes without semicolons

Since my codestyle breaks the "autodetect line to insert TCL" feature, I think a "force insert on next line" setting would be great.

Actually, TCL lines are more often on a wrong line than in the correct line. I often have to use Ctrl+F to find where my log has been inserted (it is a nightmare when you start to fold blocks) and then I have to move it manually. It also breaks the "comment all" and "remove all" features because the TCL line has been edited manually.

Thanks for your amazing extension anyway, it is still time-savy!

You can try this snippet if you'd like (select `this.foo`):
```js
export default {
    created() {
        this.foo()
        this.bar()
    },
    methods: {
        foo() {
            return 1 + 1
        },
        bar() {
            return 2 + 2
        },
    },
}
```

![image](https://user-images.githubusercontent.com/5880435/112320480-55b4a680-8caf-11eb-9e0c-582fc6ff8458.png)

**Comment by axhamre** [comment]
I'm in a TypeScript project, without semi-colons. Downgrading the version to 1.4 solved it for me:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1907343/120067948-7bc74000-c07e-11eb-977e-35be22d24651.png">


<img width="754" alt="image" src="https://user-images.githubusercontent.com/1907343/120067984-afa26580-c07e-11eb-8a04-4c137219e45b.png">

**Comment by jportella93** [comment]
Is there any way to just print the log message on the next line? I rather get consistent behavior.

**Comment by Aleksandern** [comment]
Since there is no fix for this issue I use the following extension https://github.com/shangZhengXie/vscode-console-helper

**Comment by borishere** [comment]
> Since there is no fix for this issue I use the following extension https://github.com/shangZhengXie/vscode-console-helper

Thanks for letting know the alternatives. 
Really tired of this bug.

**Comment by mribichich** [comment]
any news of this feature?
maybe a simple setting to insert into next line?

**Comment by GemKosan** [comment]
I'm also able to repro this issue. And in my React code, it often places the log statement inside a JSX block, where it's sure to fail.

Suggestion: Maybe a simple workaround would be to include a setting that sends the statement to my clipboard instead of inserting it into the cod. That way I can paste it exactly where it is needed.

**Comment by Chakroun-Anas** [comment]
Thanks everyone for the feedback and patience over the years 🙏  

This is one of the longest-standing issues and I fully understand the frustration it's caused — especially when the log insertion breaks context (like inside JSX blocks or after destructured properties).

Since this issue was first raised, Turbo Console Log has evolved a lot:

- The codebase has been refactored for better stability
- We now have **80+ tests** covering both unit and integration scenarios
- Many related edge cases have been fixed along the way

That said, there’s no “magic” fix that fits every structure or syntax style automatically. The most viable path forward — and what’s been working — is to continue fixing insertion bugs **one by one**, with the help of precise reproduction steps and fast reporting. The more clearly an issue is reported, the faster we can eliminate it.

Because this original thread is now quite old and spans multiple unrelated edge cases, I’m going to close it here. If you're still facing log insertion issues with **v2.14.0 or later**, please open a new issue with a minimal code snippet and context so it can be handled properly.

Thanks again for using TCL and for helping it improve over time ❤️
